
services:
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - kinesia_net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - kinesia_net

  db:
    image: mariadb:latest
    container_name: DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kinesiaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - kinesia_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8899:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - kinesia_net

networks:
  kinesia_net:
    driver: bridge
